version: "3.8"

services:
  web:
    image: sownthryasenthilkumar1/swarm-sample-app:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
