name: CI/CD for Docker Swarm
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/swarm-sample-app:latest ./sample-swarm-app --push

      - name: Deploy to Docker Swarm Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH-HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/swarm-sample-app:latest
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/swarm-sample-app:latest myapp_web
